service: shop-backend

useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    PGHOST: ${env:PGHOST}
    PGPORT: ${env:PGPORT}
    PGUSER: ${env:PGUSER}
    PGPASS: ${env:PGPASS}
    PGDATABASE: ${env:PGDATABASE}
plugins:
  - serverless-auto-swagger
  - serverless-webpack

functions:
  getProductList:
    handler: handler.getProductList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
